export const FETCH_SENATE_MEMBERS = 'FETCH_SENATE_MEMBERS';
export const FETCH_HOUSE_MEMBERS = 'FETCH_HOUSE_MEMBERS';
export const BOOKMARK_MEMBER = 'BOOKMARK_MEMBER';
export const FETCH_BOOKMARKED_MEMBERS = 'FETCH_BOOKMARKED_MEMBERS';
